<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert(
            [
                //a
                ['id' => '1', 'city' => 'Aceguá'],
                ['id' => '2', 'city' => 'Água Santa'],
                ['id' => '3', 'city' => 'Agudo'],
                ['id' => '4', 'city' => 'Ajuricaba'],
                ['id' => '5', 'city' => 'Alecrim'],
                ['id' => '6', 'city' => 'Alegrete'],

                ['id' => '7', 'city' => 'Alegria'],
                ['id' => '8', 'city' => 'Almirante Tamandaré do Sul'],
                ['id' => '9', 'city' => 'Alpestre'],
                ['id' => '10', 'city' => 'Alto Alegre'],
                ['id' => '11', 'city' => 'Alto Feliz'],
                ['id' => '12', 'city' => 'Alvorada'],
                ['id' => '13', 'city' => 'Amaral Ferrador'],
                ['id' => '14', 'city' => 'Ametista do Sul'],
                ['id' => '15', 'city' => 'André da Rocha'],

                ['id' => '16', 'city' => 'Anta Gorda'],
                ['id' => '17', 'city' => 'Antônio Prado'],
                ['id' => '18', 'city' => 'Arambaré'],
                ['id' => '19', 'city' => 'Araricá'],
                ['id' => '20', 'city' => 'Aratiba'],
                ['id' => '21', 'city' => 'Arroio do Meio'],
                ['id' => '22', 'city' => 'Arroio do Padre'],
                ['id' => '23', 'city' => 'Arroio do Sal'],
                ['id' => '24', 'city' => 'Arroio do Tigre'],
                ['id' => '25', 'city' => 'Arroio dos Ratos'],
                ['id' => '26', 'city' => 'Arroio Grande'],
                ['id' => '27', 'city' => 'Arvorezinha'],
                ['id' => '28', 'city' => 'Augusto Pestana'],
                ['id' => '29', 'city' => 'Áurea'],

                //b
                ['id' => '30', 'city' => 'Bagé'],
                ['id' => '31', 'city' => 'Balneário Pinhal'],
                ['id' => '32', 'city' => 'Barão'],
                ['id' => '33', 'city' => 'Barão de Cotegipe'],
                ['id' => '34', 'city' => 'Barão do Triunfo'],
                ['id' => '35', 'city' => 'Barra do Guarita'],
                ['id' => '36', 'city' => 'Barra do Quaraí'],
                ['id' => '37', 'city' => 'Barra do Ribeiro'],
                ['id' => '38', 'city' => 'Barra do Rio Azul'],
                ['id' => '39', 'city' => 'Barra Funda'],
                ['id' => '40', 'city' => 'Barracão'],
                ['id' => '41', 'city' => 'Barros Cassal'],
                ['id' => '42', 'city' => 'Benjamin Constant do Sul'],
                ['id' => '43', 'city' => 'Bento Gonçalves'],
                ['id' => '44', 'city' => 'Boa Vista das Missões'],
                ['id' => '45', 'city' => 'Boa Vista do Buricá'],
                ['id' => '46', 'city' => 'Boa Vista do Cadeado'],
                ['id' => '47', 'city' => 'Boa Vista do Incra'],
                ['id' => '48', 'city' => 'Boa Vista do Sul'],
                ['id' => '49', 'city' => 'Bom Jesus'],
                ['id' => '50', 'city' => 'Bom Princípio'],
                ['id' => '51', 'city' => 'Bom Progresso'],
                ['id' => '52', 'city' => 'Bom Retiro do Sul'],
                ['id' => '53', 'city' => 'Boqueirão do Leão'],
                ['id' => '54', 'city' => 'Bossoroca'],
                ['id' => '55', 'city' => 'Bozano'],
                ['id' => '56', 'city' => 'Braga'],
                ['id' => '57', 'city' => 'Brochier'],
                ['id' => '58', 'city' => 'Butiá'],

                //c
                ['id' => '59', 'city' => 'Caçapava do Sul'],
                ['id' => '60', 'city' => 'Cacequi'],
                ['id' => '61', 'city' => 'Cachoeira do Sul'],
                ['id' => '62', 'city' => 'Cachoeirinha'],
                ['id' => '63', 'city' => 'Cacique Doble'],
                ['id' => '64', 'city' => 'Caibaté'],
                ['id' => '65', 'city' => 'Caiçara'],
                ['id' => '66', 'city' => 'Camaquã'],
                ['id' => '67', 'city' => 'Camargo'],
                ['id' => '68', 'city' => 'Cambará do Sul'],
                ['id' => '69', 'city' => 'Campestre da Serra'],
                ['id' => '70', 'city' => 'Campina das Missões'],
                ['id' => '71', 'city' => 'Campinas do Sul'],
                ['id' => '72', 'city' => 'Campo Bom'],
                ['id' => '73', 'city' => 'Campo Novo'],
                ['id' => '74', 'city' => 'Campos Borges'],
                ['id' => '75', 'city' => 'Candelária'],
                ['id' => '76', 'city' => 'Cândido Godói'],
                ['id' => '77', 'city' => 'Candiota'],
                ['id' => '78', 'city' => 'Canela'],
                ['id' => '79', 'city' => 'Canguçu'],
                ['id' => '80', 'city' => 'Canoas'],
                ['id' => '81', 'city' => 'Canudos do Vale'],
                ['id' => '82', 'city' => 'Capão Bonito do Sul'],
                ['id' => '83', 'city' => 'Capão da Canoa'],
                ['id' => '84', 'city' => 'Capão do Cipó'],
                ['id' => '85', 'city' => 'Capão do Leão'],
                ['id' => '86', 'city' => 'Capela de Santana'],
                ['id' => '87', 'city' => 'Capitão'],
                ['id' => '88', 'city' => 'Capivari do Sul'],
                ['id' => '89', 'city' => 'Caraá'],
                ['id' => '90', 'city' => 'Carazinho'],
                ['id' => '91', 'city' => 'Carlos Barbosa'],
                ['id' => '92', 'city' => 'Carlos Gomes'],
                ['id' => '93', 'city' => 'Casca'],
                ['id' => '94', 'city' => 'Caseiros'],
                ['id' => '95', 'city' => 'Catuípe'],
                ['id' => '96', 'city' => 'Caxias do Sul'],
                ['id' => '97', 'city' => 'Centenário'],
                ['id' => '98', 'city' => 'Cerrito'],
                ['id' => '99', 'city' => 'Cerro Branco'],
                ['id' => '100', 'city' => 'Cerro Grande'],
                ['id' => '101', 'city' => 'Cerro Grande do Sul'],
                ['id' => '102', 'city' => 'Cerro Largo'],
                ['id' => '103', 'city' => 'Chapada'],
                ['id' => '104', 'city' => 'Charqueadas'],
                ['id' => '105', 'city' => 'Charrua'],
                ['id' => '106', 'city' => 'Chiapetta'],
                ['id' => '107', 'city' => 'Chuí'],
                ['id' => '108', 'city' => 'Chuvisca'],
                ['id' => '109', 'city' => 'Cidreira'],
                ['id' => '110', 'city' => 'Ciríaco'],
                ['id' => '111', 'city' => 'Colinas'],
                ['id' => '112', 'city' => 'Colorado'],
                ['id' => '113', 'city' => 'Condor'],
                ['id' => '114', 'city' => 'Constantina'],
                ['id' => '115', 'city' => 'Coqueiro Baixo'],
                ['id' => '116', 'city' => 'Coqueiros do Sul'],
                ['id' => '117', 'city' => 'Coronel Barros'],
                ['id' => '118', 'city' => 'Coronel Bicaco'],
                ['id' => '119', 'city' => 'Coronel Pilar'],
                ['id' => '120', 'city' => 'Cotiporã'],
                ['id' => '121', 'city' => 'Coxilha'],
                ['id' => '122', 'city' => 'Crissiumal'],
                ['id' => '123', 'city' => 'Cristal'],
                ['id' => '124', 'city' => 'Cristal do Sul'],
                ['id' => '125', 'city' => 'Cruz Alta'],
                ['id' => '126', 'city' => 'Cruzaltense'],
                ['id' => '127', 'city' => 'Cruzeiro do Sul'],

                //d
                ['id' => '128', 'city' => 'David Canabarro'],
                ['id' => '129', 'city' => 'Derrubadas'],
                ['id' => '130', 'city' => 'Dezesseis de Novembro'],
                ['id' => '131', 'city' => 'Dilermando de Aguiar'],
                ['id' => '132', 'city' => 'Dois Irmãos'],
                ['id' => '133', 'city' => 'Dois Irmãos das Missões'],
                ['id' => '134', 'city' => 'Dois Lajeados'],
                ['id' => '135', 'city' => 'Dom Feliciano'],
                ['id' => '136', 'city' => 'Dom Pedrito'],
                ['id' => '137', 'city' => 'Dom Pedro de Alcântara'],
                ['id' => '138', 'city' => 'Dona Francisca'],
                ['id' => '139', 'city' => 'Doutor Maurício Cardoso'],
                ['id' => '140', 'city' => 'Doutor Ricardo'],

                //e
                ['id' => '141', 'city' => 'Eldorado do Sul'],
                ['id' => '142', 'city' => 'Encantado'],
                ['id' => '143', 'city' => 'Encruzilhada do Sul'],
                ['id' => '144', 'city' => 'Engenho Velho'],
                ['id' => '145', 'city' => 'Entre Rios do Sul'],
                ['id' => '146', 'city' => 'Entre-Ijuís'],
                ['id' => '147', 'city' => 'Erebango'],
                ['id' => '148', 'city' => 'Erechim'],
                ['id' => '149', 'city' => 'Ernestina'],
                ['id' => '150', 'city' => 'Erval Grande'],
                ['id' => '151', 'city' => 'Erval Seco'],
                ['id' => '152', 'city' => 'Esmeralda'],
                ['id' => '153', 'city' => 'Esperança do Sul'],
                ['id' => '154', 'city' => 'Espumoso'],
                ['id' => '155', 'city' => 'Estação'],
                ['id' => '156', 'city' => 'Estância Velha'],
                ['id' => '157', 'city' => 'Esteio'],
                ['id' => '158', 'city' => 'Estrela'],
                ['id' => '159', 'city' => 'Estrela Velha'],
                ['id' => '160', 'city' => 'Eugênio de Castro'],

                //f
                ['id' => '161', 'city' => 'Fagundes Varela'],
                ['id' => '162', 'city' => 'Farroupilha'],
                ['id' => '163', 'city' => 'Faxinal do Soturno'],
                ['id' => '164', 'city' => 'Faxinalzinho'],
                ['id' => '165', 'city' => 'Fazenda Vilanova'],
                ['id' => '166', 'city' => 'Feliz'],
                ['id' => '167', 'city' => 'Flores da Cunha'],
                ['id' => '168', 'city' => 'Floriano Peixoto'],
                ['id' => '169', 'city' => 'Fontoura Xavier'],
                ['id' => '170', 'city' => 'Formigueiro'],
                ['id' => '171', 'city' => 'Forquetinha'],
                ['id' => '172', 'city' => 'Fortaleza dos Valos'],
                ['id' => '173', 'city' => 'Frederico Westphalen'],

                //g
                ['id' => '174', 'city' => 'Garibaldi'],
                ['id' => '175', 'city' => 'Garruchos'],
                ['id' => '176', 'city' => 'Gaurama'],
                ['id' => '177', 'city' => 'General Câmara'],
                ['id' => '178', 'city' => 'Gentil'],
                ['id' => '179', 'city' => 'Getúlio Vargas'],
                ['id' => '180', 'city' => 'Giruá'],
                ['id' => '181', 'city' => 'Glorinha'],
                ['id' => '182', 'city' => 'Gramado'],
                ['id' => '183', 'city' => 'Gramado dos Loureiros'],
                ['id' => '184', 'city' => 'Gramado Xavier'],
                ['id' => '185', 'city' => 'Gravataí'],
                ['id' => '186', 'city' => 'Guabiju'],
                ['id' => '187', 'city' => 'Guaíba'],
                ['id' => '188', 'city' => 'Guaporé'],
                ['id' => '189', 'city' => 'Guarani das Missões'],

                //h
                ['id' => '190', 'city' => 'Harmonia'],
                ['id' => '191', 'city' => 'Herval'],
                ['id' => '192', 'city' => 'Herveiras'],
                ['id' => '193', 'city' => 'Horizontina'],
                ['id' => '194', 'city' => 'Hulha Negra'],
                ['id' => '195', 'city' => 'Humaitá'],

                //i
                ['id' => '196', 'city' => 'Ibarama'],
                ['id' => '197', 'city' => 'Ibiaçá'],
                ['id' => '198', 'city' => 'Ibiraiaras'],
                ['id' => '199', 'city' => 'Ibirapuitã'],
                ['id' => '200', 'city' => 'Ibirubá'],
                ['id' => '201', 'city' => 'Igrejinha'],
                ['id' => '202', 'city' => 'Ijuí'],
                ['id' => '203', 'city' => 'Ilópolis'],
                ['id' => '204', 'city' => 'Imbé'],
                ['id' => '205', 'city' => 'Imigrante'],
                ['id' => '206', 'city' => 'Independência'],
                ['id' => '207', 'city' => 'Inhacorá'],
                ['id' => '208', 'city' => 'Ipê'],
                ['id' => '209', 'city' => 'Ipiranga do Sul'],
                ['id' => '210', 'city' => 'Iraí'],
                ['id' => '211', 'city' => 'Itaara'],
                ['id' => '212', 'city' => 'Itacurubi'],
                ['id' => '213', 'city' => 'Itapuca'],
                ['id' => '214', 'city' => 'Itaqui'],
                ['id' => '215', 'city' => 'Itati'],
                ['id' => '216', 'city' => 'Itatiba do Sul'],
                ['id' => '217', 'city' => 'Ivorá'],
                ['id' => '218', 'city' => 'Ivoti'],

                //j
                ['id' => '219', 'city' => 'Jaboticaba'],
                ['id' => '220', 'city' => 'Jacuizinho'],
                ['id' => '221', 'city' => 'Jacutinga'],
                ['id' => '222', 'city' => 'Jaguarão'],
                ['id' => '223', 'city' => 'Jaguari'],
                ['id' => '224', 'city' => 'Jaquirana'],
                ['id' => '225', 'city' => 'Jari'],
                ['id' => '226', 'city' => 'Jóia'],
                ['id' => '227', 'city' => 'Júlio de Castilhos'],

                //l
                ['id' => '228', 'city' => 'Lagoa Bonita do Sul'],
                ['id' => '229', 'city' => 'Lagoa dos Três Cantos'],
                ['id' => '230', 'city' => 'Lagoa Vermelha'],
                ['id' => '231', 'city' => 'Lagoão'],
                ['id' => '232', 'city' => 'Lajeado'],
                ['id' => '233', 'city' => 'Lajeado do Bugre'],
                ['id' => '234', 'city' => 'Lavras do Sul'],
                ['id' => '235', 'city' => 'Liberato Salzano'],
                ['id' => '236', 'city' => 'Lindolfo Collor'],
                ['id' => '237', 'city' => 'Linha Nova'],

                //m
                ['id' => '238', 'city' => 'Maçambará'],
                ['id' => '239', 'city' => 'Machadinho'],
                ['id' => '240', 'city' => 'Mampituba'],
                ['id' => '241', 'city' => 'Manoel Viana'],
                ['id' => '242', 'city' => 'Maquiné'],
                ['id' => '243', 'city' => 'Maratá'],
                ['id' => '244', 'city' => 'Marau'],
                ['id' => '245', 'city' => 'Marcelino Ramos'],
                ['id' => '246', 'city' => 'Mariana Pimentel'],
                ['id' => '247', 'city' => 'Mariano Moro'],
                ['id' => '248', 'city' => 'Marques de Souza'],
                ['id' => '249', 'city' => 'Mata'],
                ['id' => '250', 'city' => 'Mato Castelhano'],
                ['id' => '251', 'city' => 'Mato Leitão'],
                ['id' => '252', 'city' => 'Mato Queimado'],
                ['id' => '253', 'city' => 'Maximiliano de Almeida'],
                ['id' => '254', 'city' => 'Minas do Leão'],
                ['id' => '255', 'city' => 'Miraguaí'],
                ['id' => '256', 'city' => 'Montauri'],
                ['id' => '257', 'city' => 'Monte Alegre dos Campos'],
                ['id' => '258', 'city' => 'Monte Belo do Sul'],
                ['id' => '259', 'city' => 'Montenegro'],
                ['id' => '260', 'city' => 'Mormaço'],
                ['id' => '261', 'city' => 'Morrinhos do Sul'],
                ['id' => '262', 'city' => 'Morro Redondo'],
                ['id' => '263', 'city' => 'Morro Reuter'],
                ['id' => '264', 'city' => 'Mostardas'],
                ['id' => '265', 'city' => 'Muçum'],
                ['id' => '266', 'city' => 'Muitos Capões'],
                ['id' => '267', 'city' => 'Muliterno'],

                //n
                ['id' => '268', 'city' => 'Não-Me-Toque'],
                ['id' => '269', 'city' => 'Nicolau Vergueiro'],
                ['id' => '270', 'city' => 'Nonoai'],
                ['id' => '271', 'city' => 'Nova Alvorada'],
                ['id' => '272', 'city' => 'Nova Araçá'],
                ['id' => '273', 'city' => 'Nova Bassano'],
                ['id' => '274', 'city' => 'Nova Boa Vista'],
                ['id' => '275', 'city' => 'Nova Bréscia'],
                ['id' => '276', 'city' => 'Nova Candelária'],
                ['id' => '277', 'city' => 'Nova Esperança do Sul'],
                ['id' => '278', 'city' => 'Nova Hartz'],
                ['id' => '279', 'city' => 'Nova Pádua'],
                ['id' => '280', 'city' => 'Nova Palma'],
                ['id' => '281', 'city' => 'Nova Petrópolis'],
                ['id' => '282', 'city' => 'Nova Prata'],
                ['id' => '283', 'city' => 'Nova Ramada'],
                ['id' => '284', 'city' => 'Nova Roma do Sul'],
                ['id' => '285', 'city' => 'Nova Santa Rita'],
                ['id' => '286', 'city' => 'Novo Barreiro'],
                ['id' => '287', 'city' => 'Novo Cabrais'],
                ['id' => '288', 'city' => 'Novo Hamburgo'],
                ['id' => '289', 'city' => 'Novo Machado'],
                ['id' => '290', 'city' => 'Novo Tiradentes'],
                ['id' => '291', 'city' => 'Novo Xingu'],

                //o
                ['id' => '292', 'city' => 'Osório'],

                //p
                ['id' => '293', 'city' => 'Paim Filho'],
                ['id' => '294', 'city' => 'Palmares do Sul'],
                ['id' => '295', 'city' => 'Palmeira das Missões'],
                ['id' => '296', 'city' => 'Palmitinho'],
                ['id' => '297', 'city' => 'Panambi'],
                ['id' => '298', 'city' => 'Pantano Grande'],
                ['id' => '299', 'city' => 'Paraí'],
                ['id' => '300', 'city' => 'Paraíso do Sul'],
                ['id' => '301', 'city' => 'Pareci Novo'],
                ['id' => '302', 'city' => 'Parobé'],
                ['id' => '303', 'city' => 'Passa Sete'],
                ['id' => '304', 'city' => 'Passo do Sobrado'],
                ['id' => '305', 'city' => 'Passo Fundo'],
                ['id' => '306', 'city' => 'Paulo Bento'],
                ['id' => '307', 'city' => 'Paverama'],
                ['id' => '308', 'city' => 'Pedras Altas'],
                ['id' => '309', 'city' => 'Pedro Osório'],
                ['id' => '310', 'city' => 'Pejuçara'],
                ['id' => '311', 'city' => 'Pelotas'],
                ['id' => '312', 'city' => 'Picada Café'],
                ['id' => '313', 'city' => 'Pinhal'],
                ['id' => '314', 'city' => 'Pinhal da Serra'],
                ['id' => '315', 'city' => 'Pinhal Grande'],
                ['id' => '316', 'city' => 'Pinheirinho do Vale'],
                ['id' => '317', 'city' => 'Pinheiro Machado'],
                ['id' => '318', 'city' => 'Pirapó'],
                ['id' => '319', 'city' => 'Piratini'],
                ['id' => '320', 'city' => 'Planalto'],
                ['id' => '321', 'city' => 'Poço das Antas'],
                ['id' => '322', 'city' => 'Pontão'],
                ['id' => '323', 'city' => 'Ponte Preta'],
                ['id' => '324', 'city' => 'Portão'],
                ['id' => '325', 'city' => 'Porto Alegre'],
                ['id' => '326', 'city' => 'Porto Lucena'],
                ['id' => '327', 'city' => 'Porto Mauá'],
                ['id' => '328', 'city' => 'Porto Vera Cruz'],
                ['id' => '329', 'city' => 'Porto Xavier'],
                ['id' => '330', 'city' => 'Pouso Novo'],
                ['id' => '331', 'city' => 'Presidente Lucena'],
                ['id' => '332', 'city' => 'Progresso'],
                ['id' => '333', 'city' => 'Protásio Alves'],
                ['id' => '334', 'city' => 'Putinga'],

                //q
                ['id' => '335', 'city' => 'Quaraí'],
                ['id' => '336', 'city' => 'Quatro Irmãos'],
                ['id' => '337', 'city' => 'Quevedos'],
                ['id' => '338', 'city' => 'Quinze de Novembro'],

                //r
                ['id' => '339', 'city' => 'Redentora'],
                ['id' => '340', 'city' => 'Relvado'],
                ['id' => '341', 'city' => 'Rio Grande'],
                ['id' => '342', 'city' => 'Rio Pardo'],
                ['id' => '343', 'city' => 'Riozinho'],
                ['id' => '344', 'city' => 'Roca Sales'],
                ['id' => '345', 'city' => 'Rodeio Bonito'],
                ['id' => '346', 'city' => 'Rolador'],
                ['id' => '347', 'city' => 'Rolante'],
                ['id' => '348', 'city' => 'Ronda Alta'],
                ['id' => '349', 'city' => 'Rondinha'],
                ['id' => '350', 'city' => 'Roque Gonzales'],
                ['id' => '351', 'city' => 'Rosário do Sul'],

                //s
                ['id' => '352', 'city' => 'Sagrada Família'],
                ['id' => '353', 'city' => 'Saldanha Marinho'],
                ['id' => '354', 'city' => 'Salto do Jacuí'],
                ['id' => '355', 'city' => 'Salvador das Missões'],
                ['id' => '356', 'city' => 'Salvador do Sul'],
                ['id' => '357', 'city' => 'Sananduva'],
                ['id' => '358', 'city' => 'Santa Bárbara do Sul'],
                ['id' => '359', 'city' => 'Santa Cecília do Sul'],
                ['id' => '360', 'city' => 'Santa Clara do Sul'],
                ['id' => '361', 'city' => 'Santa Cruz do Sul'],
                ['id' => '362', 'city' => 'Santa Margarida do Sul'],
                ['id' => '363', 'city' => 'Santa Maria'],
                ['id' => '364', 'city' => 'Santa Maria do Herval'],
                ['id' => '365', 'city' => 'Santa Rosa'],
                ['id' => '366', 'city' => 'Santa Tereza'],
                ['id' => '367', 'city' => 'Santa Vitória do Palmar'],
                ['id' => '368', 'city' => 'Santana da Boa Vista'],
                ['id' => '369', 'city' => 'Santana do Livramento'],
                ['id' => '370', 'city' => 'Santiago'],
                ['id' => '371', 'city' => 'Santo Ângelo'],
                ['id' => '372', 'city' => 'Santo Antônio da Patrulha'],
                ['id' => '373', 'city' => 'Santo Antônio das Missões'],
                ['id' => '374', 'city' => 'Santo Antônio do Palma'],
                ['id' => '375', 'city' => 'Santo Antônio do Planalto'],
                ['id' => '376', 'city' => 'Santo Augusto'],
                ['id' => '377', 'city' => 'Santo Cristo'],
                ['id' => '378', 'city' => 'Santo Expedito do Sul'],
                ['id' => '379', 'city' => 'São Borja'],
                ['id' => '380', 'city' => 'São Domingos do Sul'],
                ['id' => '381', 'city' => 'São Francisco de Assis'],
                ['id' => '382', 'city' => 'São Francisco de Paula'],
                ['id' => '383', 'city' => 'São Gabriel'],
                ['id' => '384', 'city' => 'São Jerônimo'],
                ['id' => '385', 'city' => 'São João da Urtiga'],
                ['id' => '386', 'city' => 'São João do Polêsine'],
                ['id' => '387', 'city' => 'São Jorge'],
                ['id' => '388', 'city' => 'São José das Missões'],
                ['id' => '389', 'city' => 'São José do Herval'],
                ['id' => '390', 'city' => 'São José do Hortêncio'],
                ['id' => '391', 'city' => 'São José do Inhacorá'],
                ['id' => '392', 'city' => 'São José do Norte'],
                ['id' => '393', 'city' => 'São José do Ouro'],
                ['id' => '394', 'city' => 'São José do Sul'],
                ['id' => '395', 'city' => 'São José dos Ausentes'],
                ['id' => '396', 'city' => 'São Leopoldo'],
                ['id' => '397', 'city' => 'São Lourenço do Sul'],
                ['id' => '398', 'city' => 'São Luiz Gonzaga'],
                ['id' => '399', 'city' => 'São Marcos'],
                ['id' => '400', 'city' => 'São Martinho'],
                ['id' => '401', 'city' => 'São Martinho da Serra'],
                ['id' => '402', 'city' => 'São Miguel das Missões'],
                ['id' => '403', 'city' => 'São Nicolau'],
                ['id' => '404', 'city' => 'São Paulo das Missões'],
                ['id' => '405', 'city' => 'São Pedro da Serra'],
                ['id' => '406', 'city' => 'São Pedro das Missões'],
                ['id' => '407', 'city' => 'São Pedro do Butiá'],
                ['id' => '408', 'city' => 'São Pedro do Sul'],
                ['id' => '409', 'city' => 'São Sebastião do Caí'],
                ['id' => '410', 'city' => 'São Sepé'],
                ['id' => '411', 'city' => 'São Valentim'],
                ['id' => '412', 'city' => 'São Valentim do Sul'],
                ['id' => '413', 'city' => 'São Valério do Sul'],
                ['id' => '414', 'city' => 'São Vendelino'],
                ['id' => '415', 'city' => 'São Vicente do Sul'],
                ['id' => '416', 'city' => 'Sapiranga'],
                ['id' => '417', 'city' => 'Sapucaia do Sul'],
                ['id' => '418', 'city' => 'Sarandi'],
                ['id' => '419', 'city' => 'Seberi'],
                ['id' => '420', 'city' => 'Sede Nova'],
                ['id' => '421', 'city' => 'Segredo'],
                ['id' => '422', 'city' => 'Selbach'],
                ['id' => '423', 'city' => 'Senador Salgado Filho'],
                ['id' => '424', 'city' => 'Sentinela do Sul'],
                ['id' => '425', 'city' => 'Serafina Corrêa'],
                ['id' => '426', 'city' => 'Sério'],
                ['id' => '427', 'city' => 'Sertão'],
                ['id' => '428', 'city' => 'Sertão Santana'],
                ['id' => '429', 'city' => 'Sete de Setembro'],
                ['id' => '430', 'city' => 'Severiano de Almeida'],
                ['id' => '431', 'city' => 'Silveira Martins'],
                ['id' => '432', 'city' => 'Sinimbu'],
                ['id' => '433', 'city' => 'Sobradinho'],
                ['id' => '434', 'city' => 'Soledade'],

                //t
                ['id' => '435', 'city' => 'Tabaí'],
                ['id' => '436', 'city' => 'Tapejara'],
                ['id' => '437', 'city' => 'Tapera'],
                ['id' => '438', 'city' => 'Tapes'],
                ['id' => '439', 'city' => 'Taquara'],
                ['id' => '440', 'city' => 'Taquari'],
                ['id' => '441', 'city' => 'Taquaruçu do Sul'],
                ['id' => '442', 'city' => 'Tavares'],
                ['id' => '443', 'city' => 'Tenente Portela'],
                ['id' => '444', 'city' => 'Terra de Areia'],
                ['id' => '445', 'city' => 'Teutônia'],
                ['id' => '446', 'city' => 'Tio Hugo'],
                ['id' => '447', 'city' => 'Tiradentes do Sul'],
                ['id' => '448', 'city' => 'Toropi'],
                ['id' => '449', 'city' => 'Torres'],
                ['id' => '450', 'city' => 'Tramandaí'],
                ['id' => '451', 'city' => 'Travesseiro'],
                ['id' => '452', 'city' => 'Três Arroios'],
                ['id' => '453', 'city' => 'Três Cachoeiras'],
                ['id' => '454', 'city' => 'Três Coroas'],
                ['id' => '455', 'city' => 'Três de Maio'],
                ['id' => '456', 'city' => 'Três Forquilhas'],
                ['id' => '457', 'city' => 'Três Palmeiras'],
                ['id' => '458', 'city' => 'Três Passos'],
                ['id' => '459', 'city' => 'Trindade do Sul'],
                ['id' => '460', 'city' => 'Triunfo'],
                ['id' => '461', 'city' => 'Tucunduva'],
                ['id' => '462', 'city' => 'Tunas'],
                ['id' => '463', 'city' => 'Tupanci do Sul'],
                ['id' => '464', 'city' => 'Tupanciretã'],
                ['id' => '465', 'city' => 'Tupandi'],
                ['id' => '466', 'city' => 'Tuparendi'],
                ['id' => '467', 'city' => 'Turuçu'],

                //u
                ['id' => '468', 'city' => 'Ubiretama'],
                ['id' => '469', 'city' => 'União da Serra'],
                ['id' => '470', 'city' => 'Unistalda'],
                ['id' => '471', 'city' => 'Uruguaiana'],

                //v
                ['id' => '472', 'city' => 'Vacaria'],
                ['id' => '473', 'city' => 'Vale do Sol'],
                ['id' => '474', 'city' => 'Vale Real'],
                ['id' => '475', 'city' => 'Vale Verde'],
                ['id' => '476', 'city' => 'Vanini'],
                ['id' => '477', 'city' => 'Venâncio Aires'],
                ['id' => '478', 'city' => 'Vera Cruz'],
                ['id' => '479', 'city' => 'Veranópolis'],
                ['id' => '480', 'city' => 'Vespasiano Correa'],
                ['id' => '481', 'city' => 'Viadutos'],
                ['id' => '482', 'city' => 'Viamão'],
                ['id' => '483', 'city' => 'Vicente Dutra'],
                ['id' => '484', 'city' => 'Victor Graeff'],
                ['id' => '485', 'city' => 'Vila Flores'],
                ['id' => '486', 'city' => 'Vila Lângaro'],
                ['id' => '487', 'city' => 'Vila Maria'],
                ['id' => '488', 'city' => 'Vila Nova do Sul'],
                ['id' => '489', 'city' => 'Vista Alegre'],
                ['id' => '490', 'city' => 'Vista Alegre do Prata'],
                ['id' => '491', 'city' => 'Vista Gaúcha'],
                ['id' => '492', 'city' => 'Vitória das Missões'],

                //w
                ['id' => '493', 'city' => 'Westfalia'],

                //x
                ['id' => '494', 'city' => 'Xangri-lá'],
            ]
        );
    }
}
